#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun Jan 31 12:53:45 2021
#

import wx
import os
from dict import apps_dict
from dict import wine_dict

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 680))
        self.SetTitle("Audio Apps")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 10, wx.EXPAND, 0)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Apps")
        label_1.SetForegroundColour(wx.Colour(252, 252, 252))
        label_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Ubuntu"))
        sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.list_ctrl_1 = wx.ListBox(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_LIST | wx.LC_VRULES)
        sizer_4.Add(self.list_ctrl_1, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.TOP, 5)

        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.panel_2.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)

        label_2 = wx.StaticText(self.panel_2, wx.ID_ANY, "Wine")
        label_2.SetForegroundColour(wx.Colour(252, 252, 252))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Ubuntu"))
        sizer_5.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.list_ctrl_2 = wx.ListBox(self.panel_2, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_LIST | wx.LC_VRULES)
        sizer_5.Add(self.list_ctrl_2, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.panel_3.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)

        label_3 = wx.StaticText(self.panel_3, wx.ID_ANY, "Banks / Songs", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetForegroundColour(wx.Colour(252, 252, 252))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Ubuntu"))
        sizer_6.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.list_ctrl_3 = wx.ListBox(self.panel_3, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_LIST | wx.LC_VRULES)
        sizer_6.Add(self.list_ctrl_3, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 5)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        self.panel_4.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_3.Add(self.panel_4, 1, wx.EXPAND, 0)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)

        self.button_1 = wx.Button(self.panel_4, wx.ID_ANY, "Run")
        sizer_7.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.panel_5 = wx.Panel(self, wx.ID_ANY)
        self.panel_5.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_3.Add(self.panel_5, 1, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)

        self.button_2 = wx.Button(self.panel_5, wx.ID_ANY, "Run")
        sizer_8.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.panel_6 = wx.Panel(self, wx.ID_ANY)
        self.panel_6.SetBackgroundColour(wx.Colour(43, 73, 112))
        sizer_3.Add(self.panel_6, 1, wx.EXPAND, 0)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)

        self.button_3 = wx.Button(self.panel_6, wx.ID_ANY, "Run")
        sizer_9.Add(self.button_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.panel_6.SetSizer(sizer_9)

        self.panel_5.SetSizer(sizer_8)

        self.panel_4.SetSizer(sizer_7)

        self.panel_3.SetSizer(sizer_6)

        self.panel_2.SetSizer(sizer_5)

        self.panel_1.SetSizer(sizer_4)

        self.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

        # adiciona os itens ao listbox
        for item in sorted(apps_dict.keys()):
            self.list_ctrl_1.Append(item)

        for item in sorted(wine_dict.keys()):
            self.list_ctrl_2.Append(item)

        choices_banks_songs = ['Sons',
                                'Sons - Base DB',
                                'Modos - Calc',
                                'Carla banks',
                                'Helm banks',
                                'LV2 plugins',
                                'Rakarrack banks',
                                'ZynAddSubFX banks']

        for item in choices_banks_songs:
            self.list_ctrl_3.Append(item)

        self.list_ctrl_1.SetSelection(0)
        self.list_ctrl_2.SetSelection(0)
        self.list_ctrl_3.SetSelection(0)

        self.Bind(wx.EVT_BUTTON, self.run_apps, id=self.button_1.GetId())  # id para múltiplos botões
        self.Bind(wx.EVT_BUTTON, self.run_wine, id=self.button_2.GetId())
        self.Bind(wx.EVT_BUTTON, self.choice_select_banks_songs, id=self.button_3.GetId())

        self.Bind(wx.EVT_LISTBOX_DCLICK, self.run_apps, id=self.list_ctrl_1.GetId())
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.run_wine, id=self.list_ctrl_2.GetId())
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.choice_select_banks_songs, id=self.list_ctrl_3.GetId())


    def run_apps(self,event):
        '''Recupera o item selecionado no Listbox e chama o aplicativo'''
        choice = self.list_ctrl_1.GetSelection()
        text = self.list_ctrl_1.GetString(choice)
        print(text)
        os.system(apps_dict[text] + ' &')

    def run_wine(self, event):
        '''Recupera o item selecionado no Listbox e chama o aplicativo'''
        choice = self.list_ctrl_2.GetSelection()
        text = self.list_ctrl_2.GetString(choice)
        print(text)
        os.system("wine '" + wine_dict[text] + "' &")

    def choice_select_banks_songs(self, event):
        '''Recupera o item selecionado no Listbox e chama o banco ou música'''
        choice = self.list_ctrl_3.GetSelection()
        text = self.list_ctrl_3.GetString(choice)
        # self.root.destroy()
        if text == 'Carla banks':
            import carla_banks
            print('Executando carla_banks')
            carla_banks.carla_banks()
        elif text == 'Helm banks':
            import helm_banks
            print('Executando helm_banks')
            helm_banks.helm_banks()
        elif text == 'LV2 plugins':
            import lv2_plugins
            print('Executando lv2_plugins')
            lv2_plugins.lv2_plugins()
        elif text == 'Sons':
            import songs
            print('Executando songs')
            songs.songs()
        elif text == 'Sons - Base DB':
            os.system("libreoffice '/mnt/HD Externo/Sons/Sons.odb' &")
        elif text == 'Modos - Calc':
            os.system("libreoffice '/mnt/HD Externo/home/Documentos/Modos.ods' &")
        elif text == 'Rakarrack banks':
            import raka_banks
            print('Rakarrack banks')
            raka_banks.raka_banks()
        elif text == 'ZynAddSubFX banks':
            import zyn_banks
            print('Executando zyn_banks')
            zyn_banks.zyn_banks()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
