apps_dict={
    'Add64': 'Add64',
    'Aeolus': 'aeolus',
    'Ams': 'ams',
    'Amsynth': 'amsynth',
    'Ardour': 'ardour',
    'Arpage': 'arpage',
    'Cadence Logs': 'cadence-logs',
    'Cadence Jack Meter': 'cadence-jackmeter',
    'Cadence XY Controller': 'cadence-xycontroller',
    'Cadence Render': 'cadence-render',
    'Cecilia': 'cecilia',
    'Claudia': 'claudia',
    'Claudia-Launcher': 'claudia-launcher',
    'Drumkv1': 'drumkv1_jack',
    'Exadrums': 'exadrums',
    'Geonkick': 'geonkick',
    'Giada': 'giada',
    'Gladish': 'gladish',
    'Gtick': 'gtick',
    'Guitarix': 'guitarix',
    'Helm': 'Helm',
    'Hydrogen': 'hydrogen',
    'Impro-Visor': 'impro-visor',
    'Jack-Rack': 'jack-rack',
    'Jamin': 'jamin',
    'Lmms': 'lmms',
    'Luppp': 'luppp',
    'Meterbridge': 'meterbridge ppm',
    'Mixbus': 'Mixbus5',
    'Muse': 'muse',
    'Non-Mixer': 'non-mixer',
    'Non-Sequencer': 'non-sequencer',
    'Non-Session-Manager': 'non-session-manager',
    'Non-Timeline': 'non-timeline',
    'Padthv1': 'padthv1_jack',
    'Phasex': 'phasex',
    'Protrekkr': 'protrekkr',
    'QMidiArp': 'qmidiarp',
    'Qsampler': 'qsampler',
    'Qsynth': 'qsynth',
    'Rakarrack': 'rakarrack',
    'RaySesion': 'raysession',
    'Regrader': 'regrader',
    'Rosegarden': 'rosegarden',
    'Samplv1': 'samplv1_jack',
    'Seq24': 'seq24',
    'Sequencer24': 'qseq24',
    'SetBfree': 'setBfreeUI',
    'Synthv1': 'synthv1_jack',
    'TerminatorX': 'terminatorX',
    'Wolf-Spectrum': 'wolf-spectrum',
    'x42 Dynamic Compressor': 'x42-darc',
    'x42 Digital Peak Limiter Stereo': 'x42-dpl',
    'x42 Autotune': 'x42-fat1',
    'x42 Parametric Equalizer Stereo': 'x42-fil4',
    'x42 Matrix Mixer 8x8': 'x42-matrixmixer8x8',
    'x42 EBU R128 Meter': 'x42-meter',
    'x42 Mixer\'n\'Trigger': 'x42-mixtri',
    'x42 Simple Scope (4 channel)': 'x42-scope',
    'x42 Spectr': 'x42-spectr',
    'x42 MIDI Step Sequencer8x8': 'x42-stepseq',
    'x42 Instrument Tuner': 'x42-tuna',
    'Yoshimi': 'yoshimi',
    'ZaMaximX2': 'ZaMaximX2',
    'ZaMultiComp': 'ZaMultiComp',
    'ZaMultiCompX2': 'ZaMultiCompX2',
    'ZamAutoSat': 'ZamAutoSat',
    'ZamComp': 'ZamComp',
    'ZamCompX2': 'ZamCompX2',
    'ZamDelay': 'ZamDelay',
    'ZamDynamicEQ': 'ZamDynamicEQ',
    'ZamEQ2': 'ZamEQ2',
    'ZamGEQ31': 'ZamGEQ31',
    'ZamGate': 'ZamGate',
    'ZamGateX2': 'ZamGateX2',
    'ZamGrains': 'ZamGrains',
    'ZamHeadX2': 'ZamHeadX2',
    'ZamPhono': 'ZamPhono',
    'ZamTube': 'ZamTube',
    'ZamVerb': 'ZamVerb',
    'Zita-Bls1': 'zita-bls1',
    'Zita-Dpl1': 'zita-dpl1',
    'Zynaddbubfx': 'zynaddbubfx',
}

banks_songs = {'Carla banks':{'import_file': 'carla_banks', 'exec': 'carla_banks.carla_banks()'},
                'Sons - Musescore / Ardour / Mixbus':{'import_file': 'songs', 'exec': 'songs.songs()'},
                'Sons - Base DB':{'import_file': None, 'exec': "libreoffice '/mnt/HD Externo/Sons/Sons.odb'"}
}
