apps_dict={
    'Add64': 'Add64',
    'Aeolus': 'aeolus',
    'Ams': 'ams',
    'Amsynth': 'amsynth',
    'Ardour': 'ardour',
    'Arpage': 'arpage',
    'Cadence Logs': 'cadence-logs',
    'Cadence Jack Meter': 'cadence-jackmeter',
    'Cadence XY Controller': 'cadence-xycontroller',
    'Cadence Render': 'cadence-render',
    'Cecilia': 'cecilia',
    'Claudia': 'claudia',
    'Claudia-Launcher': 'claudia-launcher',
    'Drumkv1': 'drumkv1_jack',
    'Exadrums': 'exadrums',
    'Geonkick': 'geonkick',
    'Giada': 'giada',
    'Gladish': 'gladish',
    'Gtick': 'gtick',
    'Guitarix': 'guitarix',
    'Helm': 'Helm',
    'Hydrogen': 'hydrogen',
    'Impro-Visor': 'impro-visor',
    'Jack-Rack': 'jack-rack',
    'Jamin': 'jamin',
    'Jamulus':'Jamulus',
    'Lmms': 'lmms',
    'Luppp': 'luppp',
    'Mamba':'mamba',
    'Meterbridge': 'meterbridge ppm',
    'Mixbus': 'Mixbus6',
    'Muse': 'muse',
    'Non-Mixer': 'non-mixer',
    'Non-Sequencer': 'non-sequencer',
    'Non-Session-Manager': 'non-session-manager',
    'Non-Timeline': 'non-timeline',
    'Padthv1': 'padthv1_jack',
    'Phasex': 'phasex',
    'Protrekkr': 'protrekkr',
    'QMidiArp': 'qmidiarp',
    'Qsampler': 'qsampler',
    'Qsynth': 'qsynth',
    'Rakarrack': 'rakarrack',
    'RaySession': 'raysession',
    'Regrader': 'regrader',
    'Rosegarden': 'rosegarden',
    'Samplv1': 'samplv1_jack',
    'Seq24': 'seq24',
    'Sequencer24': 'qseq24',
    'SetBfree': 'setBfreeUI',
    'SpectMorph': 'smjack',
    'spiceAmp': '/home/lucio/bin/spiceAmp-x86_64.AppImage',
    'Synthv1': 'synthv1_jack',
    'TerminatorX': 'terminatorX',
    'tubeAmp Designer':'/home/lucio/bin/tubeAmp_Designer-x86_64.AppImage',
    'Tuner':'/home/lucio/bin/tuner',
    'Waveform11': 'Waveform11',
    'Wolf-Spectrum': 'wolf-spectrum',
    'x42 Dynamic Compressor': 'x42-darc',
    'x42 Digital Peak Limiter Stereo': 'x42-dpl',
    'x42 Autotune': 'x42-fat1',
    'x42 Parametric Equalizer Stereo': 'x42-fil4',
    'x42 Matrix Mixer 8x8': 'x42-matrixmixer8x8',
    'x42 EBU R128 Meter': 'x42-meter',
    'x42 Mixer\'n\'Trigger': 'x42-mixtri',
    'x42 Simple Scope (4 channel)': 'x42-scope',
    'x42 Spectr': 'x42-spectr',
    'x42 MIDI Step Sequencer8x8': 'x42-stepseq',
    'x42 Instrument Tuner': 'x42-tuna',
    'Yoshimi': 'yoshimi',
    'ZaMaximX2': 'ZaMaximX2',
    'ZaMultiComp': 'ZaMultiComp',
    'ZaMultiCompX2': 'ZaMultiCompX2',
    'ZamAutoSat': 'ZamAutoSat',
    'ZamComp': 'ZamComp',
    'ZamCompX2': 'ZamCompX2',
    'ZamDelay': 'ZamDelay',
    'ZamDynamicEQ': 'ZamDynamicEQ',
    'ZamEQ2': 'ZamEQ2',
    'ZamGEQ31': 'ZamGEQ31',
    'ZamGate': 'ZamGate',
    'ZamGateX2': 'ZamGateX2',
    'ZamGrains': 'ZamGrains',
    'ZamHeadX2': 'ZamHeadX2',
    'ZamPhono': 'ZamPhono',
    'ZamTube': 'ZamTube',
    'ZamVerb': 'ZamVerb',
    'Zita-Bls1': 'zita-bls1',
    'Zita-Dpl1': 'zita-dpl1',
    'Zynaddbubfx': 'zynaddsubfx',
}

wine_dict = {
    'Addictive Drums 2':
        '/home/lucio/.wine/drive_c/Program Files (x86)/XLN Audio/Addictive Drums 2/Addictive Drums 2.exe',
    'Amplitube 3': '/home/lucio/.wine/drive_c/Program Files (x86)/IK Multimedia/AmpliTube 3/Amplitube 3.exe',
    'Amplitube 4': '/home/lucio/.wine/drive_c/Program Files/IK Multimedia/AmpliTube 4/Amplitube 4.exe',
    'Analog Lab 3': '/home/lucio/.wine/drive_c/Program Files (x86)/Arturia/Analog Lab 3/Analog Lab 3.exe',
    'Amplifikation Caliburn': '/home/lucio/.wine/drive_c/Program Files/Kuassa/AmplifikationCaliburn.exe',
    'Amplifikation Creme': '/home/lucio/.wine/drive_c/Program Files/Kuassa/AmplifikationCreme.exe',
    'Amplifikation Matchlock': '/home/lucio/.wine/drive_c/Program Files/Kuassa/AmplifikationMatchlock.exe',
    'Amplifikation Vermilion': '/home/lucio/.wine/drive_c/Program Files/Kuassa/AmplifikationVermilion.exe',
    'Battery 3': '/home/lucio/.wine/drive_c/Program Files/Native Instruments/Battery 3/Battery 3.exe',
    'Battery 4': '/home/lucio/.wine/drive_c/Program Files/Native Instruments/Battery 4/Battery 4.exe',
    'Cerberus Bass Amp': '/home/lucio/.wine/drive_c/Program Files/Kuassa/CerberusBassAmp.exe',
    'Elastik': '/home/lucio/.wine/drive_c/Program Files/Elastik 3/Elastik 3.exe',
    'EZdrummer': '/home/lucio/.wine/drive_c/Program Files/Toontrack/EZdrummer/EZdrummer64.exe',
    'FM8': '/home/lucio/.wine/drive_c/Program Files/Native Instruments/FM8/FM8.exe',
    'Guitar Rig 5': '/home/lucio/.wine/drive_c/Program Files/Native Instruments/Guitar Rig 5/Guitar Rig 5.exe',
    'Independence': '/home/lucio/.wine/drive_c/Program Files (x86)/MAGIX/Independence/Independence64.exe',
    'Kontakt 6':
        '/home/lucio/.wine/drive_c/Program Files/Native Instruments/Kontakt 6 Portable/Kontakt/x64/Kontakt.exe',
    'Korg Legacy M1 Le':'/home/lucio/.wine/drive_c/Program Files (x86)/KORG/KORG Legacy/M1 Le.exe',
    'Korg Kontrol Editor':
        '/home/lucio/.wine/drive_c/Program Files (x86)/KORG/KORG KONTROL Editor/KorgKontrolEditor.exe',
    'Lounge Lizard 3':
        '/home/lucio/.wine/drive_c/Program Files (x86)/AAS/Lounge Lizard 3.0/Bin/LoungeLizard3.exe',
    'Lounge Lizard EP-4':
        '/home/lucio/.wine/drive_c/Program Files (x86)/Applied Acoustics Systems/Lounge Lizard EP-4/bin64/Lounge Lizard EP-4.exe',
    'Lounge Lizard Session 4':
        '/home/lucio/.wine/drive_c/Program Files (x86)/Applied Acoustics Systems/Lounge Lizard Session 4/bin32/Lounge Lizard Session 4.exe',
    'MIDIGuitar2': '/home/lucio/.wine/drive_c/Program Files/Jam Origin/MIDI Guitar 2/MIDIGuitar2-64bit.exe',
    'Modo Bass': '/home/lucio/.wine/drive_c/Program Files/IK Multimedia/MODO BASS/MODO BASS.exe',
    'Pianoteq 2.2': '/home/lucio/.wine/drive_c/Program Files (x86)/Pianoteq 2.2/Pianoteq22.exe',
    'Pianoteq 6 STAGE': '/home/lucio/.wine/drive_c/Program Files/Modartt/Pianoteq 6 STAGE/Pianoteq 6 STAGE.exe',
    'SampleTank 2.5': '/home/lucio/.wine/drive_c/Program Files (x86)/IK Multimedia/SampleTank 2.5/SampleTank 2.5.exe',
    'SampleTank 3': '/home/lucio/.wine/drive_c/Program Files/IK Multimedia/SampleTank 3/SampleTank 3.exe',
    'SampleTank 4': '/home/lucio/.wine/drive_c/Program Files/IK Multimedia/SampleTank 4/SampleTank 4.exe',
    'Sforzando': '/home/lucio/.wine/drive_c/Program Files/Plogue/sforzando/sforzando.exe',
    'Syntronik': '/home/lucio/.wine/drive_c/Program Files/IK Multimedia/Syntronik/Syntronik.exe',
    'Strum Session 2':
        '/home/lucio/.wine/drive_c/Program Files (x86)/Applied Acoustics Systems/Strum Session 2/bin64/Strum Session 2.exe',
    'TH-U': '/home/lucio/.wine/drive_c/Program Files/Overloud/TH-U/TH-U.exe',
    'Ultra Analog Session 2':
        '/home/lucio/.wine/drive_c/Program Files (x86)/Applied Acoustics Systems/Ultra Analog Session 2/bin32/Ultra Analog Session 2.exe',
    'Vstomp': '/home/lucio/.wine/drive_c/Program Files/Hotone/VStompAmp/VStompAmp.exe'
}

banks_songs = {'Carla banks':{'import_file': 'carla_banks', 'exec': 'carla_banks.carla_banks()'},
                'Sons - Musescore / Ardour / Mixbus':{'import_file': 'songs', 'exec': 'songs.songs()'},
                'Sons - Base DB':{'import_file': None, 'exec': "libreoffice '/mnt/HD Externo/Sons/Sons.odb'"}
}

